{"uuid": "c46e2abe-07b5-436f-9a77-f35b93e1533e", "children": ["2b6f113b-504f-41d0-8249-ddca57214edb", "e56d8e60-48bd-4e03-9056-9cc201d4ce2e"], "befores": [{"name": "init_electron_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start\n  (Driver info: chromedriver=2.36 (7ea271f92018b1eeb8e70ec6de8c29f9758a0c05),platform=Windows NT 10.0.19045 x86_64)\n\n", "trace": "  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Automation\\test_automation_infrastructure\\test_cases\\conftest.py\", line 77, in init_electron_driver\n    edriver = get_electron_driver()\n  File \"C:\\Automation\\test_automation_infrastructure\\test_cases\\conftest.py\", line 140, in get_electron_driver\n    driver = selenium.webdriver.Chrome(chrome_options=options, executable_path=get_data('Electron_Driver'))\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Automation\\test_automation_infrastructure\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750430604028, "stop": 1750430611237}], "start": 1750430604028, "stop": 1750430612153}