{"uuid": "f42c3c5b-3fa0-4173-a7c4-ded33fbd1f9e", "children": ["2b847a55-46e5-41e8-ac37-88942ff844df", "522672ce-b874-42a3-ae09-e51f33d5242b"], "befores": [{"name": "init_electron_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: no chrome binary at C:/Users/Erez/AppData/Local/Programs/todolist/Todolist.exe\n  (Driver info: chromedriver=2.36 (7ea271f92018b1eeb8e70ec6de8c29f9758a0c05),platform=Windows NT 10.0.19045 x86_64)\n\n", "trace": "  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Automation\\test_automation_final_project\\test_cases\\conftest.py\", line 77, in init_electron_driver\n    edriver = get_electron_driver()\n  File \"C:\\Automation\\test_automation_final_project\\test_cases\\conftest.py\", line 140, in get_electron_driver\n    driver = selenium.webdriver.Chrome(chrome_options=options, executable_path=get_data('Electron_Driver'))\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 76, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Automation\\test_automation_final_project\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750237164709, "stop": 1750237172003}], "start": 1750237164709, "stop": 1750237173028}